DROP DATABASE IF EXISTS BDMYSKILLS;
CREATE DATABASE BDMYSKILLS;
USE BDMYSKILLS;
DROP TABLE IF EXISTS Administrateur;
DROP TABLE IF EXISTS Professeur;
DROP TABLE IF EXISTS Etudiant;
DROP TABLE IF EXISTS Competence;
DROP TABLE IF EXISTS Acquisition;

CREATE TABLE Administrateur(
    ID INT(10) PRIMARY KEY AUTO_INCREMENT,
    Nom VARCHAR(100) NOT NULL,
    Prenom VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    MotDePasse VARCHAR(100) NOT NULL,
    Poste VARCHAR(100),
    FirstCo BOOLEAN DEFAULT '1'
);

CREATE TABLE Professeur(
    ID INT(10) PRIMARY KEY AUTO_INCREMENT,
    Nom VARCHAR(100) NOT NULL,
    Prenom VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    MotDePasse VARCHAR(100) NOT NULL,
    Classes VARCHAR(200) NOT NULL,
    Matiere VARCHAR(200) NOT NULL,
    FirstCo BOOLEAN DEFAULT '1'
);

CREATE TABLE Etudiant(
    ID INT(10) PRIMARY KEY AUTO_INCREMENT,
    Nom VARCHAR(100) NOT NULL,
    Prenom VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    MotDePasse VARCHAR(100) NOT NULL,
    Ecole VARCHAR(100) NOT NULL,
    Groupe INT(10) NOT NULL,
    Promo VARCHAR (10) NOT NULL,
    FirstCo BOOLEAN DEFAULT '1'
);

CREATE TABLE Competence(
    ID INT(10) PRIMARY KEY AUTO_INCREMENT,
    Matiere VARCHAR(100) NOT NULL,
    NomCompetence VARCHAR(100) NOT NULL,
    Acquisition INT(3) NOT NULL
);

CREATE TABLE Acquisition(
    ID INT(10) PRIMARY KEY AUTO_INCREMENT,
    ID_Competence INT(10),
    FOREIGN KEY (ID_Competence) REFERENCES Competence(ID),
    ID_Etudiant INT(10),
    FOREIGN KEY (ID_Etudiant) REFERENCES Etudiant(ID),
    Acquisition INT(3) NOT NULL
);