DROP DATABASE IF EXISTS BDMYSKILLS;
CREATE DATABASE BDMYSKILLS;
USE BDMYSKILLS;
DROP TABLE IF EXISTS Administrateur;
DROP TABLE IF EXISTS Professeur;
DROP TABLE IF EXISTS Etudiant;

CREATE TABLE Administrateur(
    ID INT(10) NOT NULL UNIQUE PRIMARY KEY,
    Nom VARCHAR(100) NOT NULL,
    Prenom VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    MotDePasse VARCHAR(100) NOT NULL,
    Poste VARCHAR(100)
);

CREATE TABLE Professeur(
    ID INT(10) NOT NULL UNIQUE PRIMARY KEY,
    Nom VARCHAR(100) NOT NULL,
    Prenom VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    MotDePasse VARCHAR(100) NOT NULL,
    Classes VARCHAR(200) NOT NULL,
    Matiere VARCHAR(200) NOT NULL
);

CREATE TABLE Etudiant(
    ID INT(10) NOT NULL UNIQUE PRIMARY KEY,
    Nom VARCHAR(100) NOT NULL,
    Prenom VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    MotDePasse VARCHAR(100) NOT NULL,
    Groupe int(10) NOT NULL,
    Promo VARCHAR (10) NOT NULL
);